<?php
/**
 * This file is part of the Memento Extension to MediaWiki
 * http://www.mediawiki.org/wiki/Extension:Memento
 *
 * @section LICENSE
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 * http://www.gnu.org/copyleft/gpl.html
 * 
 * @file
 */

// ensure that the script can't be executed outside of Mediawiki
if ( ! defined( 'MEDIAWIKI' ) ) {
	echo "Not a valid entry point";
	exit(1);
}

/**
 *
 * Special Page Implementation of a Memento TimeMap
 * @see http://mementoweb.org
 *
 * This class handles the entry point from Mediawiki and performs
 * the mediation over the real work.  The goal is to separate
 * the Mediawiki setup code from the Memento code as much as possible
 * for clarity, testing, maintainability, etc.
 *
 */
class TimeMap extends SpecialPage {

	/**
	 * Constructor
	 */
	function __construct() {
		/*
			note that these patterns are just for detecting timestamp
			pivots; error checking on the length and value of the timestamp
			happens within the class generated by the timeMapFactory
	 	*
	 	* TODO: move these member variables into TimeMapResource.
	 	*
		*/
		$this->ascendingURLPattern = "^[0-9]+\/1\/";
		$this->descendingURLPattern = "^[0-9]+\/-1\/";

		/*
			this pattern exists to detect that a timestamp pivot exists, not
			which type
		*/
		$this->pivotURLPattern = "^[0-9]+\/-*[0-9]\/";

		parent::__construct( "TimeMap" );
	}


	/**
	 * containsPivot
	 *
	 * Return true if the URL matches the pivot pattern.
	 *
	 * TODO: move this function into TimeMapResource as a static function.
	 *
	 */
	public function containsPivot($urlparam) {
		return (
			preg_match( "/$this->pivotURLPattern/", $urlparam ) == 1 );
	}

	/**
	 * isPivotAscending
	 *
	 * Return true if the URL is for a TimeMap ascending from a pivot.
	 *
	 * TODO: move this function into TimeMapResource as a static function.
	 *
	 */
	public function isPivotAscending($urlparam) {
		return (
			preg_match( "/$this->ascendingURLPattern/", $urlparam ) == 1 );
	}

	/**
	 * isPivotDescending
	 *
	 * Return true if the URL is for a TimeMap descending from a pivot.
	 *
	 * TODO: move this function into TimeMapResource as a static function.
	 *
	 */
	public function isPivotDescending($urlparam) {
		return (
			preg_match( "/$this->descendingURLPattern/", $urlparam ) == 1 );
	}

	/**
	 * timeMapFactory
	 *
	 * This function determines which TimeMap object behavior we will get
	 * based on the input.
	 *
	 * TODO: move this function into TimeMapResource as a static function.
	 *
	 */
	public function timeMapFactory( $config, $dbr, $article, $urlparam ) {

		if ( $this->containsPivot( $urlparam ) ) {
			if ( $this->isPivotAscending( $urlparam ) ) {
				$tm = new TimeMapPivotAscendingResource(
					$config, $dbr, $article );
			} elseif ( $this->isPivotDescending( $urlparam ) ) {
				$tm = new TimeMapPivotDescendingResource(
					$config, $dbr, $article );
			} else {
				$titleMessage = 'timemap';
				$textMessage = 'timemap-400-date';
				$response = $this->getOutput()->getRequest()->response();

				throw new MementoResourceException(
					$textMessage, $titleMessage,
					$out, $response, 400, array( '' )
				);
			}
		} else {
			$tm = new TimeMapFullResource( $config, $dbr, $article );
		}

		return $tm;
	}

	/**
	 * getTitle
	 *
	 * This function extracts the Title from the URL
	 */

	public function getTitleObject( $urlparam ) {

		if ( $this->isPivotAscending( $urlparam ) ) {
			$title = preg_replace(
				'/' . $this->ascendingURLPattern . '/',
				"", $urlparam );
			$title = Title::newFromText( $title );
		} elseif ( $this->isPivotDescending( $urlparam ) ) {
			$title = preg_replace(
				'/' . $this->descendingURLPattern . '/',
				"", $urlparam );
			$title = Title::newFromText( $title );
		} else {
			$title = Title::newFromText( $urlparam );
		}

		return $title;
	}

	/**
	 * The init function that is called by mediawiki when loading this
	 * SpecialPage.
	 *
	 * @param $urlpar: string; the title parameter returned by Mediawiki
	 *				which, in this case, is the URI for which we want TimeMaps
	 */
	public function execute($urlparam) {

		$out = $this->getOutput();
		$this->setHeaders();

		if ( !$urlparam ) {
			$out->addHTML( wfMessage( 'timemap-welcome-message' )->parse() );
			return;
		} else {

			$config = new MementoConfig();
			$dbr = wfGetDB( DB_SLAVE );

			try {
				// so we can use the same framework as the rest of the
				// MementoResource classes, we need an Article class
				$title = $this->getTitleObject( $urlparam );
				$article = new Article($title);
				$article->setContext($this->getContext());

				if (!$title) {
					$titleMessage = 'timemap';
					$textMessage = 'timemap-404-title';
					$response = $this->getOutput()->getRequest()->response();

					throw new MementoResourceException(
						$textMessage, $titleMessage,
						$out, $response, 400, array( "" )
					);
				}

				if ( in_array( $title->getNamespace(),
					$config->get('ExcludeNamespaces') ) ) {
					$titleMessage = 'timemap';
					$textMessage = 'timemap-403-inaccessible';
					$response = $this->getOutput()->getRequest()->response();

					throw new MementoResourceException(
						$textMessage, $titleMessage,
						$out, $response, 403, array( $urlparam )
					);
				}

				$page = $this->timeMapFactory(
					$config, $dbr, $article, $urlparam );

				$page->render();
			} catch (MementoResourceException $e) {
				MementoResource::renderError(
					$out, $e, $config->get('ErrorPageType') );
			}

		}

	}

}
